name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Zip
        run: |
          zip -r -9 gestao-pedidos-web-deploy-AspNetCoreFunction-N79gD0HGX7j2.zip *

      - name: Update
        uses: kazimanzurrashid/aws-lambda-update-action@v2.0.2
        with:
          zip-file: gestao-pedidos-web-deploy-AspNetCoreFunction-N79gD0HGX7j2.zip
        env:
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 