name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Dotnet Build
        run: |
          dotnet build .

      - name: List
        run:
          ls -la ./src/GestaoPedidos.Test/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      - name: Install dotnet Lambda
        run: |
          dotnet tool install --global Amazon.Lambda.Tools

      - name: Deploy lambda
        run: |
          dotnet lambda deploy-serverless --region us-east-1 --stack-name gestao-pedidos-web-deploy --template ./src/GestaoPedidos.Web/serverless.template --s3-bucket gestao-pedidos-web-lambda 